services:
  postiz:
    image: ghcr.io/gitroomhq/postiz-app:v2.21.2
    restart: always
    environment:
      MAIN_URL: "${MAIN_URL:-https://pixiepost.pixiewire.com}"
      FRONTEND_URL: "${FRONTEND_URL:-https://pixiepost.pixiewire.com}"
      NEXT_PUBLIC_BACKEND_URL: "${NEXT_PUBLIC_BACKEND_URL:-https://pixiepost.pixiewire.com/api}"
      BACKEND_INTERNAL_URL: "${BACKEND_INTERNAL_URL:-http://localhost:3000}"
      JWT_SECRET: "${JWT_SECRET:-joereplacethiswithnewpassword}"
      DATABASE_URL: "${DATABASE_URL:-postgresql://postiz-user:joereplacethiswithnewpassword@postiz-postgres:5432/postiz-db-local}"
      REDIS_URL: "${REDIS_URL:-redis://postiz-redis:6379}"
      IS_GENERAL: "${IS_GENERAL:-true}"
      DISABLE_REGISTRATION: "${DISABLE_REGISTRATION:-false}"
      RUN_CRON: "${RUN_CRON:-true}"
      STORAGE_PROVIDER: "${STORAGE_PROVIDER:-local}"
      UPLOAD_DIRECTORY: "${UPLOAD_DIRECTORY:-/uploads}"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "${NEXT_PUBLIC_UPLOAD_DIRECTORY:-/uploads}"
      NEXT_PUBLIC_UPLOAD_STATIC_DIRECTORY: "${NEXT_PUBLIC_UPLOAD_STATIC_DIRECTORY:-}"
      RESEND_API_KEY: "${RESEND_API_KEY:-}"
      EMAIL_FROM_ADDRESS: "${EMAIL_FROM_ADDRESS:-}"
      EMAIL_FROM_NAME: "${EMAIL_FROM_NAME:-}"
      CLOUDFLARE_ACCOUNT_ID: "${CLOUDFLARE_ACCOUNT_ID:-}"
      CLOUDFLARE_ACCESS_KEY: "${CLOUDFLARE_ACCESS_KEY:-}"
      CLOUDFLARE_SECRET_ACCESS_KEY: "${CLOUDFLARE_SECRET_ACCESS_KEY:-}"
      CLOUDFLARE_BUCKETNAME: "${CLOUDFLARE_BUCKETNAME:-}"
      CLOUDFLARE_BUCKET_URL: "${CLOUDFLARE_BUCKET_URL:-}"
      CLOUDFLARE_REGION: "${CLOUDFLARE_REGION:-auto}"
      X_API_KEY: "${X_API_KEY:-}"
      X_API_SECRET: "${X_API_SECRET:-}"
      LINKEDIN_CLIENT_ID: "${LINKEDIN_CLIENT_ID:-}"
      LINKEDIN_CLIENT_SECRET: "${LINKEDIN_CLIENT_SECRET:-}"
      REDDIT_CLIENT_ID: "${REDDIT_CLIENT_ID:-}"
      REDDIT_CLIENT_SECRET: "${REDDIT_CLIENT_SECRET:-}"
      GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID:-}"
      GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET:-}"
      BEEHIIVE_API_KEY: "${BEEHIIVE_API_KEY:-}"
      BEEHIIVE_PUBLICATION_ID: "${BEEHIIVE_PUBLICATION_ID:-}"
      LISTMONK_DOMAIN: "${LISTMONK_DOMAIN:-}"
      LISTMONK_USER: "${LISTMONK_USER:-}"
      LISTMONK_API_KEY: "${LISTMONK_API_KEY:-}"
      LISTMONK_LIST_ID: "${LISTMONK_LIST_ID:-}"
      THREADS_APP_ID: "${THREADS_APP_ID:-}"
      THREADS_APP_SECRET: "${THREADS_APP_SECRET:-}"
      FACEBOOK_APP_ID: "${FACEBOOK_APP_ID:-}"
      FACEBOOK_APP_SECRET: "${FACEBOOK_APP_SECRET:-}"
      YOUTUBE_CLIENT_ID: "${YOUTUBE_CLIENT_ID:-}"
      YOUTUBE_CLIENT_SECRET: "${YOUTUBE_CLIENT_SECRET:-}"
      TIKTOK_CLIENT_ID: "${TIKTOK_CLIENT_ID:-}"
      TIKTOK_CLIENT_SECRET: "${TIKTOK_CLIENT_SECRET:-}"
      PINTEREST_CLIENT_ID: "${PINTEREST_CLIENT_ID:-}"
      PINTEREST_CLIENT_SECRET: "${PINTEREST_CLIENT_SECRET:-}"
      DRIBBBLE_CLIENT_ID: "${DRIBBBLE_CLIENT_ID:-}"
      DRIBBBLE_CLIENT_SECRET: "${DRIBBBLE_CLIENT_SECRET:-}"
      DISCORD_CLIENT_ID: "${DISCORD_CLIENT_ID:-}"
      DISCORD_CLIENT_SECRET: "${DISCORD_CLIENT_SECRET:-}"
      DISCORD_BOT_TOKEN_ID: "${DISCORD_BOT_TOKEN_ID:-}"
      SLACK_ID: "${SLACK_ID:-}"
      SLACK_SECRET: "${SLACK_SECRET:-}"
      SLACK_SIGNING_SECRET: "${SLACK_SIGNING_SECRET:-}"
      MASTODON_URL: "${MASTODON_URL:-https://mastodon.social}"
      MASTODON_CLIENT_ID: "${MASTODON_CLIENT_ID:-}"
      MASTODON_CLIENT_SECRET: "${MASTODON_CLIENT_SECRET:-}"
      EXTENSION_ID: "${EXTENSION_ID:-}"
      OPENAI_API_KEY: "${OPENAI_API_KEY:-}"
      NEXT_PUBLIC_DISCORD_SUPPORT: "${NEXT_PUBLIC_DISCORD_SUPPORT:-}"
      NEXT_PUBLIC_POLOTNO: "${NEXT_PUBLIC_POLOTNO:-}"
      NOT_SECURED: "${NOT_SECURED:-false}"
      API_LIMIT: "${API_LIMIT:-30}"
      FEE_AMOUNT: "${FEE_AMOUNT:-0.05}"
      STRIPE_PUBLISHABLE_KEY: "${STRIPE_PUBLISHABLE_KEY:-}"
      STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY:-}"
      STRIPE_SIGNING_KEY: "${STRIPE_SIGNING_KEY:-}"
      STRIPE_SIGNING_KEY_CONNECT: "${STRIPE_SIGNING_KEY_CONNECT:-}"
      NEXT_PUBLIC_POSTIZ_OAUTH_DISPLAY_NAME: "${NEXT_PUBLIC_POSTIZ_OAUTH_DISPLAY_NAME:-Authentik}"
      NEXT_PUBLIC_POSTIZ_OAUTH_LOGO_URL: "${NEXT_PUBLIC_POSTIZ_OAUTH_LOGO_URL:-https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/authentik.png}"
      POSTIZ_GENERIC_OAUTH: "${POSTIZ_GENERIC_OAUTH:-false}"
      POSTIZ_OAUTH_URL: "${POSTIZ_OAUTH_URL:-https://auth.example.com}"
      POSTIZ_OAUTH_AUTH_URL: "${POSTIZ_OAUTH_AUTH_URL:-https://auth.example.com/application/o/authorize}"
      POSTIZ_OAUTH_TOKEN_URL: "${POSTIZ_OAUTH_TOKEN_URL:-https://auth.example.com/application/o/token}"
      POSTIZ_OAUTH_USERINFO_URL: "${POSTIZ_OAUTH_USERINFO_URL:-https://authentik.example.com/application/o/userinfo}"
      POSTIZ_OAUTH_CLIENT_ID: "${POSTIZ_OAUTH_CLIENT_ID:-}"
      POSTIZ_OAUTH_CLIENT_SECRET: "${POSTIZ_OAUTH_CLIENT_SECRET:-}"
      POSTIZ_OAUTH_SCOPE: "${POSTIZ_OAUTH_SCOPE:-openid profile email}"
      NEXT_PUBLIC_SENTRY_DSN: "${NEXT_PUBLIC_SENTRY_DSN:-}"
      SENTRY_SPOTLIGHT: "${SENTRY_SPOTLIGHT:-0}"
      NX_ADD_PLUGINS: "${NX_ADD_PLUGINS:-false}"
      DUB_TOKEN: "${DUB_TOKEN:-}"
      DUB_API_ENDPOINT: "${DUB_API_ENDPOINT:-https://api.dub.co}"
      DUB_SHORT_LINK_DOMAIN: "${DUB_SHORT_LINK_DOMAIN:-dub.sh}"
      SHORT_IO_SECRET_KEY: "${SHORT_IO_SECRET_KEY:-}"
      KUTT_API_KEY: "${KUTT_API_KEY:-}"
      KUTT_API_ENDPOINT: "${KUTT_API_ENDPOINT:-https://kutt.it/api/v2}"
      KUTT_SHORT_LINK_DOMAIN: "${KUTT_SHORT_LINK_DOMAIN:-kutt.it}"
      LINK_DRIP_API_KEY: "${LINK_DRIP_API_KEY:-}"
      LINK_DRIP_API_ENDPOINT: "${LINK_DRIP_API_ENDPOINT:-https://api.linkdrip.com/v1/}"
      LINK_DRIP_SHORT_LINK_DOMAIN: "${LINK_DRIP_SHORT_LINK_DOMAIN:-dripl.ink}"
    volumes:
      - postiz-config:/config
      - postiz-uploads:/uploads
    ports:
      - "3000:5000"
    networks:
      - postiz-network
      - coolify
    depends_on:
      postiz-postgres:
        condition: service_healthy
      postiz-redis:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.docker.network=coolify
      - traefik.http.routers.pixiepost.rule=Host(`pixiepost.pixiewire.com`)
      - traefik.http.routers.pixiepost.entrypoints=websecure
      - traefik.http.routers.pixiepost.tls=true
      - traefik.http.services.pixiepost.loadbalancer.server.port=5000

  postiz-postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTIZ_POSTGRES_PASSWORD:-joereplacethiswithnewpassword}"
      POSTGRES_USER: "${POSTIZ_POSTGRES_USER:-postiz-user}"
      POSTGRES_DB: "${POSTIZ_POSTGRES_DB:-postiz-db-local}"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - postiz-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 5

  postiz-redis:
    image: redis:7.2
    restart: always
    volumes:
      - postiz-redis-data:/data
    networks:
      - postiz-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres-volume:
  postiz-config:
  postiz-uploads:
  postiz-redis-data:

networks:
  coolify:
    external: true
  postiz-network:
    driver: bridge
